[workspace]
members = ["fnmock", "fnmock-derive", "fnmock-example-project"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["rzeppa.jakob@gmail.com"]
license = "Apache-2.0"
repository = "https://github.com/jakob-rzeppa/rust-helpers-macros"
